#Documentation:
# https://github.com/marketplace/actions/hashicorp-setup-terraform
# https://registry.terraform.io/providers/Snowflake-Labs/snowflake

name: "CI"

#configures the pipeline to automatically run when a change is pushed on the
#main branch of the repository.
on:
  pull_request:
 # push:
  #  branches:
    #- main
  
permissions:
  issues: write
  pull-requests: write

# https://docs.github.com/en/actions/about-github-actions/understanding-github-actions
jobs: # Job: set of steps in workflow executed on same runner (shell script, or an action)
  snowflake-terraform-plan:
    name: "Snowflake Terraform Job"
    runs-on: ubuntu-latest #Runner: server that runs workflows when triggered. Can run single job at a time.
    defaults:
        run:
            working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4
       # with:
        #  github-token: ${{ secrets.GIT_TF_TOKEN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.0"
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

        # To avoid bug during CI, First run "terraform fmt" on local machine plz!
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: set test vars and select workspace
        id: testvar
        if: github.event_name == 'pull_request'
        run: cp ../vars/test.auto.tfvars var.auto.tfvars && terraform workspace select test

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        
      - name: Terraform TEST Plan
        id: test_plan
        if: github.event_name == 'pull_request'
        run: terraform plan -no-color
        continue-on-error: true

      - uses: actions/github-script@v7
        if: github.event_name == 'pull_request' || github.event_name == 'push'
        env:
          PLAN: "terraform\n${{ steps.test_plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GIT_TF_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.test_plan.outcome }}\`
            
            <details><summary>Show Plan</summary>
            
            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`
            
            </details>
            
            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

     
  
  ######################################################################################################
  #Gestion/controle des version des fichiers sql 

  # https://github.com/Snowflake-Labs/schemachange

  schemachange-dry-run:
    runs-on: ubuntu-latest
    needs: snowflake-terraform-plan
    defaults:
        run:
            working-directory: objects_statements
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Python 3.8.x
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8.x

      - name: Run schemachange
        env:
          SF_ACCOUNT: ${{ secrets.SF_ACCOUNT }}
          SF_USERNAME: ${{ secrets.SF_USERNAME }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
          python --version
          echo "Step 1: Installing schemachange"
          pip install schemachange==4.0.1

      - name: DRY RUN in case of PR
        env:
          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
        if: github.event_name == 'pull_request'
        run: |
          echo ${{ secrets.SF_ACCOUNT }}
          echo $SF_ACCOUNT
          echo "Step PR: Running schemachange DRY RUN"
          schemachange --config-folder schema_change_config --connections-file-path schema_change_config/connection.toml  --connection-name test -c TEST_POC_VISEO_DB.MONITORING_LAYER.CHANGE_HISTORY --dry-run
        #  schemachange -a ${{ secrets.SF_ACCOUNT }} -u  ${{ secrets.SF_USERNAME }} -r TEST_POC_VISEO_ROLE -w TEST_WH -d TEST_POC_VISEO_DB --vars '{"warehouse": "TEST_WH"}' -c TEST_POC_VISEO_DB.MONITORING_LAYER.CHANGE_HISTORY --create-change-history-table --dry-run       
          
 ######################################################################################################
